version: "3.8"

services: 
    api:
        # restart: always
        image: blinovvitaly/apidpsystem
        build: 
            context: .
            dockerfile: ApiDPSystem/Dockerfile
        volumes:
           - ./:/etc    #нужно уточнить. Пытаюсь сохранять все данные,
                        #чтобы каждый раз при обновлении приложения не перезапускать контейнер.
        ports:
            - 8081:80
        depends_on:
            - mssql

    nginx:
        image: nginx:latest
        volumes:
            - ./ApiDPSystem/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 90:80

    mssql:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${PASSWORD}
        volumes:
            - ./mssql-data:/var/opt/mssql
        ports:
            - 8082:1433